version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/projectAgapov:/var/www/hello-luca/projectAgapov
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
    depends_on:
      - php
    container_name: nginx-container

  php:
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/projectAgapov:/var/www/hello-luca/projectAgapov
    depends_on:
      - mysql
    container_name: php-container

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ads_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 54321
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysql-container
    deploy:
      resources:
        limits:
          memory: 2g

  bind:
    build:
      context: ./bind
    container_name: bind
    ports:
      - "53:53/udp"
